#############################################################################
# Makefile for building: Bignumber
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Sep 17 18:29:59 2017
# Project:  Bignumber.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Bignumber.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -g -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -Iinclude
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -L/home/jisiyu/src/Qt/BigNumber/lib/ -lgtest_main -lgtest -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		bignumber.cpp \
		bignumberimpl.cpp 
OBJECTS       = main.o \
		bignumber.o \
		bignumberimpl.o
DIST          = README.md \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Bignumber.pro
QMAKE_TARGET  = Bignumber
DESTDIR       = 
TARGET        = Bignumber

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/jisiyu/src/Qt/BigNumber/lib/libgtest.a /home/jisiyu/src/Qt/BigNumber/lib/libgtest_main.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Bignumber.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile Bignumber.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
deployment.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile Bignumber.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Bignumber1.0.0 || $(MKDIR) .tmp/Bignumber1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Bignumber1.0.0/ && (cd `dirname .tmp/Bignumber1.0.0` && $(TAR) Bignumber1.0.0.tar Bignumber1.0.0 && $(COMPRESS) Bignumber1.0.0.tar) && $(MOVE) `dirname .tmp/Bignumber1.0.0`/Bignumber1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Bignumber1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp bignumber.h \
		bignumberimpl.h \
		include/gtest/gtest.h \
		include/gtest/internal/gtest-internal.h \
		include/gtest/internal/gtest-port.h \
		include/gtest/internal/gtest-port-arch.h \
		include/gtest/internal/custom/gtest-port.h \
		include/gtest/internal/gtest-tuple.h \
		include/gtest/gtest-message.h \
		include/gtest/internal/gtest-string.h \
		include/gtest/internal/gtest-filepath.h \
		include/gtest/internal/gtest-type-util.h \
		include/gtest/gtest-death-test.h \
		include/gtest/internal/gtest-death-test-internal.h \
		include/gtest/gtest-param-test.h \
		include/gtest/internal/gtest-param-util.h \
		include/gtest/internal/gtest-linked_ptr.h \
		include/gtest/gtest-printers.h \
		include/gtest/internal/custom/gtest-printers.h \
		include/gtest/internal/gtest-param-util-generated.h \
		include/gtest/gtest_prod.h \
		include/gtest/gtest-test-part.h \
		include/gtest/gtest-typed-test.h \
		include/gtest/gtest_pred_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

bignumber.o: bignumber.cpp bignumber.h \
		bignumberimpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bignumber.o bignumber.cpp

bignumberimpl.o: bignumberimpl.cpp bignumberimpl.h \
		include/gtest/gtest.h \
		include/gtest/internal/gtest-internal.h \
		include/gtest/internal/gtest-port.h \
		include/gtest/internal/gtest-port-arch.h \
		include/gtest/internal/custom/gtest-port.h \
		include/gtest/internal/gtest-tuple.h \
		include/gtest/gtest-message.h \
		include/gtest/internal/gtest-string.h \
		include/gtest/internal/gtest-filepath.h \
		include/gtest/internal/gtest-type-util.h \
		include/gtest/gtest-death-test.h \
		include/gtest/internal/gtest-death-test-internal.h \
		include/gtest/gtest-param-test.h \
		include/gtest/internal/gtest-param-util.h \
		include/gtest/internal/gtest-linked_ptr.h \
		include/gtest/gtest-printers.h \
		include/gtest/internal/custom/gtest-printers.h \
		include/gtest/internal/gtest-param-util-generated.h \
		include/gtest/gtest_prod.h \
		include/gtest/gtest-test-part.h \
		include/gtest/gtest-typed-test.h \
		include/gtest/gtest_pred_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bignumberimpl.o bignumberimpl.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/Bignumber/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/Bignumber/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/Bignumber/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/Bignumber/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/Bignumber/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Bignumber/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

